[package]
name = "native-apps"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
native-userspace = { path = "../native-runtime" }

[features]
default = []
guest = []
reply-negative = ["guest"]

[[bin]]
name = "counter-service"
path = "src/counter-service.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "smoke-client"
path = "src/smoke-client.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "native-supervisor"
path = "src/supervisor.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "selftest-process"
path = "src/selftest-process.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "selftest-ipc"
path = "src/selftest-ipc.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "selftest-service"
path = "src/selftest-service.rs"
required-features = ["guest"]
test = false
bench = false

[[bin]]
name = "selftest-elf"
path = "src/selftest-elf.rs"
required-features = ["guest"]
test = false
bench = false
